trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  RG: aks-study-1
  CLUSTER: aks-study
  LOCATION: eastus
  NODE_SIZE: Standard_D2s_v3
  ACR: acrstudy

steps:
- task: AzureCLI@2
  displayName: "Criar AKS"
  inputs:
    azureSubscription: 'aks-service-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      set -e

      echo "Criando Resource Group..."
      az group create --name $RG --location $LOCATION

      echo "Criando AKS..."
      az aks create \
        --resource-group $RG \
        --name $CLUSTER \
        --location $LOCATION \
        --node-count 1 \
        --node-vm-size $NODE_SIZE \
        --enable-managed-identity \
        --tier free \
        --auto-upgrade-channel none \
        --node-os-upgrade-channel None \
        --generate-ssh-keys

      echo "Pegando credenciais..."
      az aks get-credentials \
        --resource-group $RG \
        --name $CLUSTER \
        --overwrite-existing

      echo "Validando cluster..."
      kubectl get nodes

      az aks update \
        --name $CLUSTER \
        --resource-group $RG \
        --attach-acr $ACR