trigger:
- none

variables:
  ENV: hom
  ACR_NAME: acrstudy
  IMAGE_NAME: api1
  RESOURCE_GROUP: rg-study-1
  AKS_NAME: aks-study

stages:
- stage: BuildAndDeploy
  jobs:
  - job: BuildPushDeploy
    pool:
      vmImage: 'ubuntu-latest'

    steps:

    # 🔐 Login na Azure
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'aks-service-connection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Logando no ACR..."
          az acr login --name $(ACR_NAME)

    # 🐳 Build + Push
    - script: |
        IMAGE_TAG=$(Build.BuildId)
        IMAGE_FULL=$(ACR_NAME).azurecr.io/$(IMAGE_NAME)-$(ENV):$IMAGE_TAG

        echo "Buildando imagem $IMAGE_FULL..."

        docker build -t $IMAGE_FULL 005-aks-app-information/api1
        docker push $IMAGE_FULL

        echo "##vso[task.setvariable variable=IMAGE_TAG]$IMAGE_TAG"
        echo "##vso[task.setvariable variable=IMAGE_FULL]$IMAGE_FULL"
      displayName: Build and Push Docker Image

    # ✏️ Substituir tag no deployment
    - script: |
        sed -i "s|__IMAGE__|$(IMAGE_FULL)|g" 005-aks-app-information/api1/.k8s/deployment.yaml
        sed -i "s|__ENV__|$(ENV)|g" 005-aks-app-information/api1/.k8s/deployment.yaml
        sed -i "s|__ENV__|$(ENV)|g" 005-aks-app-information/api1/.k8s/service.yaml
      displayName: Inject image into deployment

    # ☸️ Conectar no AKS
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'aks-service-connection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az aks get-credentials \
            --resource-group aks-study-1 \
            --name $(AKS_NAME) \
            --overwrite-existing

    # 🚀 Deploy no Kubernetes
    - script: |
        kubectl apply -f 005-aks-app-information/api1/.k8s/deployment.yaml -n hom
        kubectl apply -f 005-aks-app-information/api1/.k8s/service.yaml -n hom
      displayName: Deploy to AKS
