apiVersion: apps/v1
kind: Deployment
metadata:
  name: api1-hom
  labels:
    app: api1-hom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api1-hom
  template:
    metadata:
      labels:
        app: api1-hom
    spec:
      containers:
      - name: api1-hom
        image: acrstudy.azurecr.io/api1-hom:90
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi
